### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by szepeviktor** [matt-allan/hours#16]
While trying to dig deep into your code:

- `grep -rn 'if.*(.*!' app/` lists all typecastings: the last one is the only proper one `if (! $project instanceof Project)`
- in app/Report.php:120 `new CarbonInterval(null)` may not be [a good idea](https://carbon.nesbot.com/reference/#doc-method-CarbonInterval-__construct)

**Comment by szepeviktor** [comment]
PHPStan gives highly crippled results but here is `phpstan.neon`

```yaml
parameters:
    level: 4
    paths:
        - %currentWorkingDirectory%/app/
    ignoreErrors:
         - '#^Call to an undefined( static)? method (App|Illuminate|Carbon)\\#'
```
